<?php


/**
 * Skeleton subclass for representing a row from the 'person' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 29 15:44:41 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Person extends BasePerson {
    public function __toString() {
        return $this->getName();
    }
    
    /**
     * Get categories for this person
     * @return array(Category, Category, ... )
     */
    public function getCategories() {
        $c = new Criteria();
        $c->addAscendingOrderByColumn(PersonCategoryPeer::CATEGORY_ID);
        $rels = $this->getPersonCategorysJoinCategory($c);
        $cats = array();
        foreach ($rels as $rel) {
            $cats[] = $rel->getCategory();
        }
        
        return $cats;
    }
} // Person
