<?php


/**
 * Skeleton subclass for performing query and update operations on the 'person' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.2 on:
 *
 * Fri Oct 29 15:44:41 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PersonPeer extends BasePersonPeer {
    /**
     * Get active people, which are to be displayed
     * @return array(Person, Person, ...)
     */
    public static function getActive() {
        $c = new Criteria();
        $c->add(PersonPeer::VALIDATED_AT, null, Criteria::ISNOTNULL);
        return PersonPeer::doSelect($c);
    }
} // PersonPeer
