prod:
  base_url: 'http://sananton.io'
all:
  base_url: 'http://sananton.com'
  website_name: SANANTON.IO
  help_link: 'http://twitter.com/itrebal'
  email:
    from: no-reply@sananton.io
    name: SANANTON.IO