propel:
  _attributes:
    package: lib.model
    defaultIdMethod: native
  category:
    _attributes: { phpName: Category }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '20', required: true, index: unique }
    slug: { type: VARCHAR, size: '20', required: true, index: unique }
  person:
    _attributes: { phpName: Person }
    id: { type: INTEGER, size: '11', primaryKey: true, autoIncrement: true, required: true }
    name: { type: VARCHAR, size: '255', required: true }
    website: { type: VARCHAR, size: '255', required: true, index: unique }
    email: { type: VARCHAR, size: '255', required: true, index: unique }
    image: { type: VARCHAR, size: '255', required: true }
    validated_at: { type: TIMESTAMP }
    created_at: { type: TIMESTAMP }
    updated_at: { type: TIMESTAMP }
  person_category:
    _attributes: { phpName: PersonCategory }
    person_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: person, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    category_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: category, foreignReference: id, onDelete: RESTRICT, onUpdate: CASCADE }
    _uniques: { category_slug: [person_id, category_id] }
  person_hash:
    _attributes: { phpName: PersonHash }
    person_id: { type: INTEGER, size: '11', primaryKey: true, required: true, foreignTable: person, foreignReference: id, onDelete: CASCADE, onUpdate: CASCADE }
    hash: { type: VARCHAR, size: '255', required: true, primaryKey: true, index: unique }
    used: { type: BOOLEAN, required: true, default: false }
    created_at: { type: TIMESTAMP }
